### PR TITLE
Fire ice sprite enemies

### PR DESCRIPTION
**Pull request by PyroPoro**

### CODE REVIEW

**Comment by PyroPoro** [comment]
includes the torch and terminals

**Review by AlekseyPanas — CHANGES_REQUESTED** [review]
Requested changes in DMs

**Review by AlekseyPanas — APPROVED** [review]
Looks good now!

**Review by 1whatleytay — COMMENTED** [review]
#92 branch target is weird.

**Review by 1whatleytay — APPROVED** [review]
Approving and CC'ing my comments here. My browser can't bother to load the whole PR so it's harder to find the points where I left comments. 

https://github.com/AlekseyPanas/CSC404_Magengaard/pull/92

**Pull request merged**
