### PR TITLE
Arena prototype

### PR DESCRIPTION
**Pull request by PyroPoro**
Prototype of the test arena for Wednesday

Would like some feedback. Some areas are not accessible and are intended for either levitation spells or ladders, neither of which are implemented.

Physics is very janky with the current character movement system, but it will be fixed once the movement system gets changed to character controller.

### CODE REVIEW

**Comment by 1whatleytay** [comment]
I guess I have to clone it to see it? 😅

**Comment by 1whatleytay** [comment]
Sure, this looks good.

**Review by 1whatleytay — APPROVED** [review]
LGTM, a bit cheesed that probuilder is a project dependency now though, I guess that's just the way.

**Review by AlekseyPanas — APPROVED** [review]
Looks awesome

**Pull request merged**
